int64 imu_freq
int64 lid_freq
int64 odom_freq
int64[] cams_freq

int64 map_size
int64 oct_num
int64 new_idxs
int64 upd_idxs
int64 scan_size
int64 num_feats
int64 num_reject
float64 res_mean
float64 off_mean

float64 imu_time
float64 state_time
float64 map_time
float64 total_time

float64 imu_mean
float64 state_mean
float64 map_mean
float64 total_mean

float64 imu_max
float64 state_max
float64 map_max
float64 total_max