/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/hesai/pandar"
            imu_topic:  "/alphasense_driver_ros/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
            
        preprocess:
            lidar_type: 5                # AVIA = 1, VELO16 = 2, OUST64 = 3, MID360 = 4, XT32 = 5, L515 = 6, VELO32 = 7
            scan_line: 64
            scan_rate: 10
            timestamp_unit: 0                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 1.5

        cameras:
            frame_rate: 20
            cam_topics: ["/alphasense_driver_ros/cam0/color/image_rect", "/alphasense_driver_ros/cam1/color/image_rect", "/alphasense_driver_ros/cam2/color/image_rect"]
            cam_intrinsics : [704.504153913163, 0.0, 703.6790228113778, 0.0, 708.8501128392297, 562.7041625276061, 0.0, 0.0, 1.0,
                              706.2598489736399, 0.0, 705.2120115507148, 0.0, 721.3570861335752, 541.7756390155482, 0.0, 0.0, 1.0,
                              701.1738642199008, 0.0, 700.2460544875661, 0.0, 719.7612949714033, 532.0306325030654, 0.0, 0.0, 1.0]
            T_cam_lidars: [0.000742889940738678, -0.046884626150131226, -0.04570324346423149,
                           -0.008015308529138565, -0.10740606486797333, -0.057117655873298645,
                           -0.018912456929683685, -0.06331472843885422, -0.07150501012802124]
            R_cam_lidars: [0.0035327, 0.9999856, 0.0040441, 0.0132611, 0.0039969, -0.9999041, -0.9999058, 0.0035859, -0.0132468,
                           -0.9999453, 0.0104511, -0.0001823, -0.0000112, -0.0185110, -0.9998286, -0.0104527, -0.9997740, 0.0185101,
                           0.9999302, -0.0118147, 0.0001027, 0.0001875, 0.0071730, -0.9999743, 0.0118136, 0.9999045, 0.0071748]

        mapping:
            acc_cov: 0.001202028502700754
            gyr_cov: 0.0003655255870559997
            b_acc_cov: 5.2639003774643306e-05
            b_gyr_cov: 7.394478709479997e-06
            fov_degree:    180.0
            det_range:     150.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
            extrinsic_T: [ -0.005, -0.010, 0.044 ]
            extrinsic_R: [ -0.0169719, -0.9998519,  0.0028286,
                            0.9998560, -0.0169719,  0.0000240,
                            0.0000240,  0.0028286,  0.9999960 ]

        publish:
            path_en: true                # true: publish Path
            effect_map_en: false         # true: publish Effects
            map_en: true                 # true: publish Map cloud
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: false      # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame
            pub_map_n_secs: 10            # publish rate of map cloud

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.