/**:
    ros__parameters:

        mapping:
            map_resolution: 0.1
            pub_map_n_secs: 10 

        publish:
            map: true
            scan: true
            markers: true
            odometry: true
            analytics: true
            tf: true

        lidar:
            type: 1 # LIVOX = 1, VELODYNE = 2, OUSTER = 3, HESAI = 4
            rate: 10
            scan_lines: 64
            vertical_fov: 59.0
            min_range: 0.0
            max_range: 100.0
            topic:  "/boxi/livox/points"
            t_imu_lidar: [0.018, -0.021, 0.268]
            r_imu_lidar: [1.000, 0.004, -0.003, -0.001]
            
        imu:
            rate: 500
            acc_noise: 0.1
            gyr_noise: 0.1
            acc_bias: 0.0001
            gyr_bias: 0.0001
            topic:  "/boxi/stim320/imu"
