/**:
    ros__parameters:

        mapping:
            map_resolution: 0.1
            pub_map_n_secs: 10

        publish:
            map: true
            scan: true
            markers: true
            odometry: true
            analytics: true
            tf: true 

        lidar:
            type: 4 # LIVOX = 1, VELODYNE = 2, OUSTER = 3, HESAI = 4
            rate: 10
            scan_lines: 64
            vertical_fov: 40.0
            min_range: 0.0
            max_range: 100.0
            topic:  "/boxi/hesai/points"
            t_imu_lidar: [0.017, -0.026, 0.171] 
            r_imu_lidar: [0.001, 0.001, 0.708, 0.706]

        imu:
            rate: 500
            acc_noise: 1.0
            gyr_noise: 0.1
            acc_bias: 0.01
            gyr_bias: 0.001
            topic:  "/boxi/stim320/imu"